jobs:
- job: build
  pool:
    name: 'Hosted VS2017'  # name of the pool to run this job in
    demands: 
      - msbuild
      - visualstudio
      - vstest
  steps:
  - checkout: self  
    clean: false
    submodules: true  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules

  - task: NuGetToolInstaller@0
    displayName: 'Install Nuget tool'

  - task: PowerShell@2
    displayName: 'PowerShell Script build.ps1'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '--env=wac --pack --version=0.1.$(Build.BuildNumber) --output-hashing all'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'IIS-WAC-MyGet'
